[config]
transactions = 100
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "arpc"
url = "http://fra.corvus-labs.io:20202"
x_token = ""
kind = "arpc"

[[endpoint]]
name = "grpc"
url = "http://fra.corvus-labs.io:10101"
x_token = ""
kind = "yellowstone"
