[config]
transactions = 10000
account = "ComputeBudget111111111111111111111111111111"
commitment = "processed"

[[endpoint]]
name = "arpc"
url = "http://fra.corvus-labs.io:20202"
kind = "arpc"

[[endpoint]]
name = "grpc"
url = "http://fra.corvus-labs.io:10101"
kind = "yellowstone"
